<a href="https://colab.research.google.com/github/Edy940/Edy940/blob/main/Atividade_Pos_Graduacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [151]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()




In [74]:
df = pd.read_csv('/content/testeRestaurante_.csv',encoding = "ISO-8859-1", sep=';')
df.drop(['Dia'], axis='columns', inplace=True)
df.head(15)



Previsao Temperatura Umidade  Vento      Vender
0     chuva        frio  normal    sim  parmegiana
1     chuva    moderado    alta    sim  parmegiana
2       sol      quente    alta    não  parmegiana
3       sol      quente    alta    sim  parmegiana
4       sol    moderado    alta    não  parmegiana
5   nublado        frio  normal    sim    feijoada
6   nublado      quente    alta    não    feijoada
7   nublado      quente  normal    não    feijoada
8   nublado    moderado    alta    sim    feijoada
9     chuva        frio  normal    não    feijoada
10    chuva    moderado    alta    não    feijoada
11    chuva    moderado  normal    não    feijoada
12      sol        frio  normal    não    feijoada
13      sol    moderado  normal    sim    feijoada
14      sol        frio  normal  vento         NaN

In [81]:
df.dropna(axis = 0, how='any', inplace=True)
df

Previsao Temperatura Umidade Vento      Vender
0     chuva        frio  normal   sim  parmegiana
1     chuva    moderado    alta   sim  parmegiana
2       sol      quente    alta   não  parmegiana
3       sol      quente    alta   sim  parmegiana
4       sol    moderado    alta   não  parmegiana
5   nublado        frio  normal   sim    feijoada
6   nublado      quente    alta   não    feijoada
7   nublado      quente  normal   não    feijoada
8   nublado    moderado    alta   sim    feijoada
9     chuva        frio  normal   não    feijoada
10    chuva    moderado    alta   não    feijoada
11    chuva    moderado  normal   não    feijoada
12      sol        frio  normal   não    feijoada
13      sol    moderado  normal   sim    feijoada

In [82]:
target=df.Vender
inputs=df.drop('Vender', axis='columns')

In [165]:
dummies = pd.get_dummies(inputs.Previsao)
dummies.head(3)

chuva  nublado  sol
0      1        0    0
1      1        0    0
2      0        0    1

In [84]:
dummies = pd.get_dummies(inputs.Temperatura)
dummies.head(3)

frio  moderado  quente
0     1         0       0
1     0         1       0
2     0         0       1

In [85]:
dummies = pd.get_dummies(inputs.Umidade)
dummies.head(3)

alta  normal
0     0       1
1     1       0
2     1       0

In [86]:
dummies = pd.get_dummies(inputs.Vento)
dummies.head(3)

não  sim
0    0    1
1    0    1
2    1    0

In [87]:
inputs = pd.concat([inputs, dummies], axis = 'columns')
inputs.head(3)

Previsao Temperatura Umidade Vento  não  sim
0    chuva        frio  normal   sim    0    1
1    chuva    moderado    alta   sim    0    1
2      sol      quente    alta   não    1    0

In [88]:
x_teste_restaurante = df.iloc[:, 0:4].values
x_teste_restaurante

array([['chuva', 'frio', 'normal', 'sim'],
       ['chuva', 'moderado', 'alta', 'sim'],
       ['sol', 'quente', 'alta', 'não'],
       ['sol', 'quente', 'alta', 'sim'],
       ['sol', 'moderado', 'alta', 'não'],
       ['nublado', 'frio', 'normal', 'sim'],
       ['nublado', 'quente', 'alta', 'não'],
       ['nublado', 'quente', 'normal', 'não'],
       ['nublado', 'moderado', 'alta', 'sim'],
       ['chuva', 'frio', 'normal', 'não'],
       ['chuva', 'moderado', 'alta', 'não'],
       ['chuva', 'moderado', 'normal', 'não'],
       ['sol', 'frio', 'normal', 'não'],
       ['sol', 'moderado', 'normal', 'sim']], dtype=object)

In [89]:
y_teste_restaurante = df.iloc[:, 4].values
y_teste_restaurante

array(['parmegiana', 'parmegiana', 'parmegiana', 'parmegiana',
       'parmegiana', 'feijoada', 'feijoada', 'feijoada', 'feijoada',
       'feijoada', 'feijoada', 'feijoada', 'feijoada', 'feijoada'],
      dtype=object)

In [90]:
from sklearn.preprocessing import LabelEncoder
label_encoder_Previsao = LabelEncoder()
label_encoder_Temperatura = LabelEncoder()
label_encoder_Umidade = LabelEncoder()
label_encoder_Vento = LabelEncoder()


In [91]:
x_teste_restaurante[:,0] = label_encoder_Previsao.fit_transform(x_teste_restaurante[:,0])
x_teste_restaurante[:,1] = label_encoder_Temperatura.fit_transform(x_teste_restaurante[:,1])
x_teste_restaurante[:,2] = label_encoder_Umidade.fit_transform(x_teste_restaurante[:,2])
x_teste_restaurante[:,3] = label_encoder_Vento.fit_transform(x_teste_restaurante[:,3])





In [92]:
x_teste_restaurante

array([[0, 0, 1, 1],
       [0, 1, 0, 1],
       [2, 2, 0, 0],
       [2, 2, 0, 1],
       [2, 1, 0, 0],
       [1, 0, 1, 1],
       [1, 2, 0, 0],
       [1, 2, 1, 0],
       [1, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [2, 0, 1, 0],
       [2, 1, 1, 1]], dtype=object)

In [109]:
naive_teste_restaurante = GaussianNB()
naive_teste_restaurante.fit(x_teste_restaurante, y_teste_restaurante)

GaussianNB(priors=None, var_smoothing=1e-09)

In [195]:
#Previsao_Sol(2), Temperatura_Frio(0), Umidade_Normal(1), Vento_Sim(1)

PrevisaoDeVenda = naive_teste_restaurante.predict([[2,0,1,1]])



In [196]:
PrevisaoDeVenda

array(['feijoada'], dtype='<U10')

In [125]:
naive_teste_restaurante.classes_

array(['feijoada', 'parmegiana'], dtype='<U10')

In [126]:
naive_teste_restaurante.class_count_

array([9., 5.])

In [188]:
((naive_teste_restaurante.class_prior_)*100)


array([64.28571429, 35.71428571])